# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout
      - uses: actions/checkout@v2
        
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Download the file
        with:
          url: "http://www.drwindows.de/news/feed"

      # Runs a single command using the runners shell
      - name: Rename file
        run: mv feed feed_$(date +%d-%m-%Y).rss
        
      # Check git status
      - name: Git status
        run: git status
        
      # Git Commit and Push
      - name: Git Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add new feed
          push_options: '--force'
